man = input("Name a friend: ")
teacher = input("Name a teacher: ")
neat_trick = input("Whats something you can do that consistently brings in the ladies: ")
loved_one = input("What are the last words you would say to a loved one: ")
character_trait = input("Character Trait: ")
emotion = input("Name an Emotion: ")
song = input("What song would get the aux taken off of you: ")

print()
print("You have just woken up from your " + teacher + " induced daydream")
print("only to realise that the most " + character_trait + " man in school is looking in your direction")
print("..." + man + " is staring right at your phone, and spotify is open")
print(man + " now knows you listen to " + song + " and a quick glance over reveals a face solely expressing " + emotion)
print("you decide the best course of action is to lean over and whisper in their ear " + loved_one)
print("then before " + man + " can get " + teacher + "'s attention, you distract the class with your inhuman ability to " + neat_trick)
